version: '2'
services:
    web:
        build: ./app_server
        volumes:
            - ./app_server:/code
        working_dir: /code
        command: python3 -u main.py
        ports:
            - "15000:5000"
        expose:
            - "5000"
        links:
            - dynamodb
            - ai
    ai:
        build: ./ai
        volumes:
            - ./ai:/code
        working_dir: /code
        command: python3 -u main.py
        ports:
            - "16000:5000"
        expose:
            - "5000"
        links:
            - dynamodb
    dynamodb:
        image: deangiberson/aws-dynamodb-local:latest
        expose:
            - "8000"
        ports:
            - "18000:8000"
